"""Machine-generated PIO machine code and parameters for rp2pio.StateMachine.

This machine-generated Python library contains the RP2040 PIO state machine
machine code, state machine parameters, and optionally a class of interval
timings. Because this library is generated by a generally-purpose formatter,
this documentation is necessarily general, refer to the code around this
project to understanding the meaning of the code.


Provenance:

This file was created by:
assembly_code/reformat_pioasm.py

This formatter drew from a text-separated-values file likely exported from
a spreadsheet. The developer likely chose to develop the assembly code by
using a spreadsheet to manage both the logic and the timing intervals.

The text-separated-values source file is: assembly_code/assembly_code.txt


Side Set Pins:

In addition to the output pins, The RP2040 PIO has the ability to optionally
set additional pins with each operation, the side-set pins. These may be used
for example to send out diagnostic data, or enable/disable a data bus.
Unfortunately, the choice of the use of side-set pins is set in the assembly
code. In an effort to give the end user an ability to choose if they wish to
use side-set capability in the application or not, this formatter has the
option to output machine code variations customized for different number of
side-set pins desired. It also has the option to output code variations for
logically-inverted side-set pins.

The meaning of the side set pins can not be determined in this machine-
generated file. See elsewhere in the project for the meaning of these pins.


StateMachine Program:

None is a either a memoryview object suitable for
use as a program for a rp2pio.StateMachine, or it is tuple of memoryview
objects. If it is a tuple, the index is the desired number of side-set pins,
and if negative, the desired number of logically-inverted side-set pins.

None is a either dictionary of parameters suitable for
rp2pio.StateMachine or a function that returns such a dictionary. If it is
a function, the one function parameter is the desired number of side-set pins,
and if negative, the desired number of logically-inverted side-set pins.

None, if present, is a class of interval timings. Likely, the
source spreadsheet has an additional column of interval names, additional
expressions, and a pivot table to re-calculate timing intervals on the fly
as the programmer worked on the logic. This formatter can read the interval
names and calculate timings and output a class of class constants for each
interval names. The meaning of each interval name can not be determined
from this machine-generated file. See elsewhere in the project for the
meaning of these interval names."""


#  DO NOT EDIT THIS FILE  DO NOT EDIT THIS FILE  DO NOT EDIT THIS FILE


## Tuple of programs for rp2pio.StateMachine
## The index is the number of desired sideset pins.
machine_code = (
    # index = 0: No desired sideset_pins.
    memoryview(
        b"\x30\x60\x41\x00\x03\xa0\x30\x60\x44\x00\x30\x60\x0b\xa0\x47\x00"
        b"\x50\x60\xe0\x80\x03\xa2\x27\xe0\x01\x61\x42\xa0\x4c\x00\x0b\xa0"
        b"\x28\x60\x51\x00\x89\x00\xe0\x80\x03\xa2\x27\xe0\x01\x61\x42\xa0"
        b"\x56\x00\x0b\xa0\x28\x60\x20\x00\x5c\x00\xa0\x80"
    ).cast("H"),
    # index = 1: One desired sideset_pins.
    memoryview(
        b"\x30\x70\x41\x10\x03\xb0\x30\x70\x44\x10\x30\x70\x0b\xb0\x47\x10"
        b"\x50\x70\xe0\x90\x03\xb2\x27\xf0\x01\x71\x42\xb0\x4c\x10\x0b\xb0"
        b"\x28\x70\x51\x10\x89\x10\xe0\x90\x03\xb2\x27\xf0\x01\x71\x42\xb0"
        b"\x56\x10\x0b\xb0\x28\x70\x20\x10\x5c\x10\xa0\x80"
    ).cast("H"),
)


#  DO NOT EDIT THIS FILE  DO NOT EDIT THIS FILE  DO NOT EDIT THIS FILE


## Sideset settings from the assembly code.
SIDESET_PINS = 1
SIDESET_ENABLE = False


## A function that produces parameters for rp2pio.StateMachine"
## example: rp2pio.StateMachine(
##                              my_machine_code_variable[sideset_pins],"
##                              **pio_kwargs(sideset_pins),"
##                              ...(additional parameters)...,"
##                              )
def pio_kwargs(sideset_pins=0):
    "Get parameters appropriate for the desired side-set pin count."
    pin_count = min(SIDESET_PINS, abs(sideset_pins))
    enable = bool(pin_count) and SIDESET_ENABLE
    return {
        "sideset_enable": enable,
        "sideset_pin_count": pin_count,
    }


#  DO NOT EDIT THIS FILE  DO NOT EDIT THIS FILE  DO NOT EDIT THIS FILE


class IntervalTimings:  # pylint: disable=too-few-public-methods
    """Named timing intervals. All are PIO clock tics.
    See documentation elsewhere in this project for the meaning of these names.
    """

    AST = 1
    ATS = 1
    BRK = 4
    DAT = 4
    MAB = 3
    MAF = 3
    MBB = 2
    STA = 4
    STP = 4
    TDA = 4
    TSA = 4
    WAT = 2
